1. Array
2. scipy
3. Matematika dasar
  a. penjumlahan
  b. perkalian
  c. pangkat
  d. trigonometri
  e. eksponen
  f. bilangan imaginer
  

## Menggunakan scipy

In [1]:
import scipy

In [2]:
from scipy import array

In [3]:
from scipy import * # mengambil semua yang ada dalam scipy

In [4]:
sin

<ufunc 'sin'>

In [5]:
integrate

NameError: name 'integrate' is not defined

In [6]:
linspace

<function numpy.core.function_base.linspace>

In [11]:
x=linspace(0,10,11)

In [22]:
sin(x)


array([ 0.        ,  0.84147098,  0.90929743,  0.14112001, -0.7568025 ,
       -0.95892427, -0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849,
       -0.54402111])

## Array
1. menggunakan fungsi 'array'

In [13]:
A=[1,2,3] # list

In [14]:
A


[1, 2, 3]

In [15]:
B=array(A)

In [16]:
B

array([1, 2, 3])

In [17]:
2*B

array([2, 4, 6])

In [18]:
2*A

[1, 2, 3, 1, 2, 3]

In [19]:
array(2*A)

array([1, 2, 3, 1, 2, 3])

In [20]:
sin(B)

array([ 0.84147098,  0.90929743,  0.14112001])

In [21]:
cos(B)

array([ 0.54030231, -0.41614684, -0.9899925 ])

### menggunakan fungsi 'linspace'


In [23]:
linspace(0,10,11)

array([  0.,   1.,   2.,   3.,   4.,   5.,   6.,   7.,   8.,   9.,  10.])

### menggunakan 'zeros' atau 'ones'

In [25]:
C=zeros([3,3])

In [26]:
C

array([[ 0.,  0.,  0.],
       [ 0.,  0.,  0.],
       [ 0.,  0.,  0.]])

In [27]:

C[0]

array([ 0.,  0.,  0.])

In [28]:
C[0,0]

0.0

In [29]:
C[0,0]=1

In [30]:
C

array([[ 1.,  0.,  0.],
       [ 0.,  0.,  0.],
       [ 0.,  0.,  0.]])

In [31]:
C[1,1]=1

In [32]:
C

array([[ 1.,  0.,  0.],
       [ 0.,  1.,  0.],
       [ 0.,  0.,  0.]])

In [33]:
C[2,2]=1

In [34]:
C

array([[ 1.,  0.,  0.],
       [ 0.,  1.,  0.],
       [ 0.,  0.,  1.]])

In [36]:
D=ones([3,3])

In [37]:
D

array([[ 1.,  1.,  1.],
       [ 1.,  1.,  1.],
       [ 1.,  1.,  1.]])

In [38]:
D[0,1]=89

In [39]:
D

array([[  1.,  89.,   1.],
       [  1.,   1.,   1.],
       [  1.,   1.,   1.]])

In [40]:
Y=zeros([14,14])

In [41]:
Y

array([[ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
         0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
         0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
         0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
         0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
         0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
         0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
         0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
         0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
         0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
         0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
         0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0., 

In [42]:
## Matemati Dasar

In [43]:
### Penjumlahan


In [44]:
A=4+4234234235

In [45]:
A

4234234239

In [46]:
345*9

3105

In [47]:
2**3 # pangkat

8

In [48]:
5**3

125

In [49]:
9**3

729

In [50]:
4*0.5

2.0

In [51]:
8**(1/3)

2.0

In [52]:
4-5

-1

In [53]:
1/3

0.3333333333333333

In [54]:
## Trigonometri

In [55]:
pi

3.141592653589793

In [56]:
sin(pi/2)

1.0

In [57]:
cos(0)

1.0

In [58]:
tan(pi/4)

0.99999999999999989

In [59]:
sec(pi/2)

NameError: name 'sec' is not defined

In [60]:
secant

NameError: name 'secant' is not defined

In [61]:
sin

<ufunc 'sin'>

In [62]:
1/sin(pi/2)

1.0

In [63]:
## Eksponen

In [64]:
exp

<ufunc 'exp'>

In [65]:

exp(3)

20.085536923187668

In [66]:
exp(1)

2.7182818284590451

In [67]:
log(10)

2.3025850929940459

In [68]:
log(exp(10))

10.0

In [69]:
log10

<function numpy.lib.scimath.log10>

In [70]:
log10(1000)

3.0

In [71]:
sqrt

<function numpy.lib.scimath.sqrt>

In [72]:
sqrt(4)

2.0

In [73]:
4**0.5

2.0

In [74]:
### Bilangan Imajiner

In [75]:
sqrt(-1)

1j

In [76]:
2+2j

(2+2j)

In [77]:
Y=zeros(3)

In [79]:
Y[0,0]=10

IndexError: too many indices for array

In [80]:
Y

array([ 0.,  0.,  0.])

In [81]:
Y[0]=2

In [82]:
Y

array([ 2.,  0.,  0.])

In [83]:
Y[1]=2j

TypeError: can't convert complex to float