# Contoh penggunaan for loop
1. 'for loop' sederhana
2. menghitung jumlah dengan 'for loop'
3. Mengisi elemen array dengan menggunakan 'for loop'
4. Mengisi elemen matriks admitansi dengan menggunakan 'for loop'

In [62]:
from scipy import sin, cos, linspace, pi,zeros
for x in [1,2,3]:
    print(x,sin(x),cos(x))

1 0.841470984808 0.540302305868
2 0.909297426826 -0.416146836547
3 0.14112000806 -0.9899924966


In [63]:
a=linspace(0,2*pi,100)

In [64]:
for x in a:
    print(x,sin(x), cos(x))

0.0 0.0 1.0
0.0634665182543 0.0634239196566 0.997986676472
0.126933036509 0.126592453574 0.991954812831
0.190399554763 0.18925124436 0.981928697263
0.253866073017 0.251147987181 0.967948701396
0.317332591272 0.312033445698 0.950071117741
0.380799109526 0.37166245566 0.928367933016
0.44426562778 0.429794912089 0.902926538287
0.507732146035 0.4861967361 0.87384937707
0.571198664289 0.540640817456 0.841253532831
0.634665182543 0.592907929055 0.805270257531
0.698131700798 0.642787609687 0.766044443119
0.761598219052 0.690079011482 0.723734038105
0.825064737306 0.734591708658 0.678509411557
0.888531255561 0.776146464292 0.630552667085
0.951997773815 0.81457595205 0.580056909571
1.01546429207 0.84972542995 0.527225467611
1.07893081032 0.881453363448 0.472271074773
1.14239732858 0.909631995355 0.415415013002
1.20586384683 0.934147860265 0.356886221592
1.26933036509 0.954902241444 0.296920375328
1.33279688334 0.971811568324 0.235758935509
1.3962634016 0.984807753012 0.173648177667
1.4597299198

In [65]:
J=0
for i in [1,2,3,4,5]:
    J=J+i

In [66]:
J

15

In [67]:
a=[1,2,3,4,5,6,7,8,9]
K=0
for i in a:
    K=K+i
    

In [68]:
K

45

In [69]:
range

range

In [70]:
range(10)

range(0, 10)

In [71]:
for x in range(10):
    print(x)

0
1
2
3
4
5
6
7
8
9


In [72]:
range(1,10)

range(1, 10)

In [73]:
for x in range(1,101):
    print(x)

1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26
27
28
29
30
31
32
33
34
35
36
37
38
39
40
41
42
43
44
45
46
47
48
49
50
51
52
53
54
55
56
57
58
59
60
61
62
63
64
65
66
67
68
69
70
71
72
73
74
75
76
77
78
79
80
81
82
83
84
85
86
87
88
89
90
91
92
93
94
95
96
97
98
99
100


In [74]:
J=0
for x in range(1,101):
    J=J+x**2

In [75]:
J

338350

In [76]:
sum


<function sum>

In [77]:
sum(range(1,101))

5050

In [78]:
Y=zeros([14,14])

In [79]:
Y

array([[ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
         0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
         0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
         0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
         0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
         0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
         0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
         0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
         0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
         0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
         0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
         0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0., 

In [80]:
for x in range(14):
    Y[x,x]=93274972947

In [81]:
Y

array([[  9.32749729e+10,   0.00000000e+00,   0.00000000e+00,
          0.00000000e+00,   0.00000000e+00,   0.00000000e+00,
          0.00000000e+00,   0.00000000e+00,   0.00000000e+00,
          0.00000000e+00,   0.00000000e+00,   0.00000000e+00,
          0.00000000e+00,   0.00000000e+00],
       [  0.00000000e+00,   9.32749729e+10,   0.00000000e+00,
          0.00000000e+00,   0.00000000e+00,   0.00000000e+00,
          0.00000000e+00,   0.00000000e+00,   0.00000000e+00,
          0.00000000e+00,   0.00000000e+00,   0.00000000e+00,
          0.00000000e+00,   0.00000000e+00],
       [  0.00000000e+00,   0.00000000e+00,   9.32749729e+10,
          0.00000000e+00,   0.00000000e+00,   0.00000000e+00,
          0.00000000e+00,   0.00000000e+00,   0.00000000e+00,
          0.00000000e+00,   0.00000000e+00,   0.00000000e+00,
          0.00000000e+00,   0.00000000e+00],
       [  0.00000000e+00,   0.00000000e+00,   0.00000000e+00,
          9.32749729e+10,   0.00000000e+00,   0.00000000e+0

In [82]:
for x in range(14):
    for y in range(14):
        if x!=y:
            Y[x,y]=-3
            

In [83]:
Y

array([[  9.32749729e+10,  -3.00000000e+00,  -3.00000000e+00,
         -3.00000000e+00,  -3.00000000e+00,  -3.00000000e+00,
         -3.00000000e+00,  -3.00000000e+00,  -3.00000000e+00,
         -3.00000000e+00,  -3.00000000e+00,  -3.00000000e+00,
         -3.00000000e+00,  -3.00000000e+00],
       [ -3.00000000e+00,   9.32749729e+10,  -3.00000000e+00,
         -3.00000000e+00,  -3.00000000e+00,  -3.00000000e+00,
         -3.00000000e+00,  -3.00000000e+00,  -3.00000000e+00,
         -3.00000000e+00,  -3.00000000e+00,  -3.00000000e+00,
         -3.00000000e+00,  -3.00000000e+00],
       [ -3.00000000e+00,  -3.00000000e+00,   9.32749729e+10,
         -3.00000000e+00,  -3.00000000e+00,  -3.00000000e+00,
         -3.00000000e+00,  -3.00000000e+00,  -3.00000000e+00,
         -3.00000000e+00,  -3.00000000e+00,  -3.00000000e+00,
         -3.00000000e+00,  -3.00000000e+00],
       [ -3.00000000e+00,  -3.00000000e+00,  -3.00000000e+00,
          9.32749729e+10,  -3.00000000e+00,  -3.00000000e+0

$y_{ij} = g_{ij} + j b_{ij}$

$Y_{ij}=-y_{ij}$ dengan syarat $i \neq j$

$Y_{ij} = G_{ij} + jB_{ij}$

In [84]:
G=zeros([14,14])
B=zeros([14,14])

for x in range(14):
    for y in range(14):
        if x!=y:
            G[x,y]=-3
            B[x,y]=-8